### ISSUE TITLE
Conflicts with files in static folder

### ISSUE THREAD

**Issue by RinatValiullov** [Lectrum/react-workshop#2]
Во время установки и разворачивания проекта столкнулся со следующими конфликтами. 
На вопрос о перезаписи, перезаписал всё. С чем это связано и является ли большой ошибкой?

![image](https://user-images.githubusercontent.com/9755333/47576561-38544480-d95e-11e8-9bc7-c6b6a834373c.png)

**Comment by dvakatsiienko** [comment]
@RinatValiullov Привет! Дело в том, что генератор хочет перезаписать старые файлы более новой версией. Это нормальное поведение 🙂
